# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='desctiption',
            new_name='description',
        ),
    ]
