# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_auto_20180103_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvote',
        ),
        migrations.AddField(
            model_name='upvote',
            name='answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answer.Answer'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answer.Question'),
        ),
    ]
