# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_auto_20180103_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upvote',
            old_name='questions',
            new_name='user',
        ),
    ]
